Dan-Bam/IndiStraw-MSA-Server

.gitignore
movie/manage.py
movie/movie/asgi.py
movie/movie/settings.py
movie/movie/urls.py
movie/movie/wsgi.py
movie/requirements.txt

- Django-Movie 프로젝트 생성
- Django-Movie 프로젝트 생성
- .gitignore을 통해 .env 등의 파일을 커밋사항에서 제외
- 간단한 프로젝트 생성이라 장고에 대해서 모르거나 궁금한점 있으시면 comment 남겨주세요!

🎉 :: Django-Movie 프로젝트 생성

---

account/build.gradle.kts
account/src/main/resources/application.yml

- 클라우드 타입 배포를 위한 mariaDB 의존성 추가
- 복붙하면서 생긴 필요없는 properties 삭제

🔀 :: mariaDB 의존성 추가

---

account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt

🔀 :: name size 수정

---

account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignUpRequest.kt

- 요구사항에 따른 비밀번호 !@#$%^&*?~ 특수문자 정규표현식 추가

🔀 :: 특수문자 정규표현식 추가

---

account/src/main/kotlin/com/indistraw/account/adapter/input/request/SignInRequest.kt

- signInRequest password  빠진 정규표현식 추가
- 깜빡하고 커밋을 깜빡해서.. 여러개 pr 죄송합니다 ㅠㅠ

🔀 :: 로그인 특수문자 정규표현식 추가

---

account/src/main/kotlin/com/project/indistraw/account/application/common/error/exception/IndiStrawAccountException.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/error/handler/GlobalExceptionHandler.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/error/response/ErrorResponse.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/AccountNotFoundException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/PasswordNotMatchException.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckAccountIdUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckAccountIdService.kt
account/src/main/kotlin/com/project/indistraw/global/security/filter/ExceptionHandlerFilter.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/InvalidTokenTypeException.kt
account/src/test/kotlin/com/project/indistraw/service/CheckAccountIdServiceTest.kt

- id 중복 검사 기능 추가하였습니다.
- id를 중복 검사하여 있으면 409 status를 던지는 기능을 추가하였습니다.
- 패키지 명을 덜 바꾼 클래스들 패키지명을 수정하였습니다.

🔀 :: id 중복 검사 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedAccountIdException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedPhoneNumberException.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
account/src/test/kotlin/com/project/indistraw/service/CheckPhoneNumberServiceTest.kt

- 핸드폰 번호 중복 검사 로직 추가
- 핸드폰 번호가 중복이라면 409 status를 보내게 구현하였습니다.
- 중복된 id 예외처리가 빠진 부분을 커밋하였습니다.
- 해당 로직에 관한 테스트 코드를 작성하였습니다.

🔀 :: 중복된 핸드폰 번호 검사 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/CoolSmsAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/properties/CoolSmsProperties.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandAuthCodePersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AuthCodeConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AuthCodeEntity.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/repository/AuthCodeRepository.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/SendAuthCodeUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandAuthCodePort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/SendMessagePort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SendAuthCodeService.kt
account/src/main/kotlin/com/project/indistraw/account/domain/AuthCode.kt
account/src/main/resources/application.yml
account/src/test/kotlin/com/project/indistraw/service/SendAuthCodeServiceTest.kt

- 핸드폰 번호로 인증번호 발송 기능을 추가하였습니다.
- coolsms를 연동하여 주어진 핸드폰 번호로 인증번호를 발송하는 기능을 구현하였습니다.
- 해당 로직에 관한 테스트 코드를 작성하였습니다.

🔀 :: 인증번호 발송 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandRefreshTokenPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryAccountPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryRefreshTokenPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/RefreshTokenConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/RefreshTokenEntity.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/repository/RefreshTokenRepository.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/ReissueTokenUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandRefreshTokenPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/QueryAccountPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/QueryRefreshTokenPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/TokenGeneratePort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/TokenParsePort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/dto/TokenDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/ReissueTokenService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SignInService.kt
account/src/main/kotlin/com/project/indistraw/global/event/SaveRefreshTokenEvent.kt
account/src/main/kotlin/com/project/indistraw/global/event/SaveRefreshTokenEventHandler.kt
account/src/main/kotlin/com/project/indistraw/global/security/adapter/PasswordEncodeAdapter.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/FilterConfig.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/main/kotlin/com/project/indistraw/global/security/filter/JwtRequestFilter.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/TokenGenerateAdapter.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/TokenParseAdapter.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/ExpiredRefreshTokenException.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/InvalidTokenException.kt
account/src/test/kotlin/com/project/indistraw/service/ReissueTokenServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/SignInServiceTest.kt

- 토큰 재발급 기능을 추가하였습니다.
- 토큰 재발급 컨트롤러, 서비스를 추가하였습니다.
- filter에서 구현체에 의존을 삭제하고 추상화를 의존하게 만들었습니다.
- refreshToken을 redis에 저장하는 event를 만들어 reissueTokenService, signInService에서 사용하도록 만들었습니다.
- 해당 기능에 대한 테스트 코드를 작성하였습니다.

🔀 :: 토큰 재발급 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdatePasswordRequest.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/UpdatePasswordUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdatePasswordDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/AccountSecurityPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePasswordService.kt
account/src/main/kotlin/com/project/indistraw/global/security/adapter/AccountSecurityAdapter.kt
account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt

- 비밀번호 변경 기능을 추가하였습니다.
- 비밀번호 변경 성공시 205 status를 반환하도록 구현하였습니다.

🔀 :: 비밀번호 변경 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/UpdateAccountProfileUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/test/kotlin/com/project/indistraw/service/UpdateAccountProfileServiceTest.kt

- 프로필 수정 기능을 추가하였습니다.
- 프로필 수정 성공시 205 status를 반환하도록 구현하였습니다.
- /update/profile endPoint를 권한이 있어야 요청 할 수 있도록 구현하였습니다.
- /change/password -> /update/password로 endPoint를 변경하였습니다.

🔀 :: 프로필 수정 기능 추가

---

account/src/test/kotlin/com/project/indistraw/service/VerifyAuthCodeServiceTest.kt

- 인증코드 검증 테스트코드 이벤트 정의 안된 이슈를 해결했습니다.
- createAuthenticationEvent의 동작 정의가 안된걸 해결하였습니다.

🔀 :: 인증코드 검증 테스트코드 이벤트 정의 안된 이슈 해결

---

account/src/main/kotlin/com/project/indistraw/account/application/port/input/AccountProfileDetailUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
account/src/test/kotlin/com/project/indistraw/service/AccountProfileDetailServiceTest.kt

- 프로필 조회 기능을 추가하였습니다.
- 프로필 조회 기능을 추가하였습니다.
- 해당 기능에 관한 테스트 코드를 추가하였습니다.

🔀 :: 프로필 조회 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/AccountWithdrawUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/AccountWithdrawService.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/test/kotlin/com/project/indistraw/service/AccountWithdrawServiceTest.kt

- 계정 탈퇴 기능 추가
- 계정 탈퇴 요청을 하면 204 status를 반환하도록 구현하였습니다.
- 권한이 있어야 요청을 보낼 수 있도록 구현하였습니다.

🔀 :: 계정 탈퇴 기능 추가

---

account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

- 비밀번호 변경 권한 이슈를 해결 하였습니다.
- 비밀번호 변경 endPoint의 권한을 삭제하였습니다.

🔀 :: 비밀번호 변경 권한 이슈 해결

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandAuthenticationPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/error/ErrorCode.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/util/AuthenticationValidator.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/TooManyAuthenticationRequestException.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandAuthenticationPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/FindAccountIdService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SendAuthCodeService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePasswordService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/VerifyAuthCodeService.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Authentication.kt
account/src/main/kotlin/com/project/indistraw/global/event/CreateAuthenticationEvent.kt
account/src/main/kotlin/com/project/indistraw/global/event/CreateAuthenticationEventHandler.kt
account/src/main/kotlin/com/project/indistraw/global/event/DeleteAuthenticationEvent.kt
account/src/main/kotlin/com/project/indistraw/global/event/DeleteAuthenticationEventHandler.kt
account/src/main/kotlin/com/project/indistraw/global/event/SaveRefreshTokenEventHandler.kt
account/src/test/kotlin/com/project/indistraw/service/FindAccountIdServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/SendAuthCodeServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/SignInServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/SignUpServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/VerifyAuthCodeServiceTest.kt

- id 찾기, 비밀번호 변경에서 authentication 확인 기능을 추가하였습니다.
- authentication을 확인하는 공통 코드를 줄이고자, authentiacationValidator 클래스를 추가하여 중복 코드를 줄였습니다.
- 인증 코드 요청을 1시간 이내 5번 초과 할 시 예외처리를 하였습니다.

🔀 :: authentication 확인 로직 추가

---

.gitignore
file/api/models.py
file/api/serializers.py
file/api/urls.py
file/api/views.py
file/file/settings.py
file/file/urls.py
file/requirements.txt

file 업로드 구현하였습니다.
file 업로드 구현하였습니다. s3 로 업로드하고 db 를 한번 거쳐갑니다.
+ 급하게 코드짜느라 최적화시키지 못했습니다. 바쁜 일정이 끝나면 db를 거치지 않고 바로 s3 로 업로드하는 로직을 구현할 예정입니다.

✨ :: Django file 업로드

---

.github/workflows/Django-CI.yml
.github/workflows/Spring-CI.yml

Django, Spring의 pr branch를 수정하였습니다.

🔀 :: PR Branch 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

- 전화번호 검사 비밀번호 변경, 회원가입 구분 로직을 추가하였습니다.
- 기존의 비밀번호 변경시 전화번호 검사 할때, 409가 나와야 성공으로 받아드리고 다음 단계로 넘어가야한다는 문제점이 생겨
전화번호 검사 enum 타입을 추가하여 요청 파라미터에 추가하여 따로 검사를 하도록 구현하였습니다.

🔀 :: 전화번호 검사 비밀번호 변경, 회원가입 구분 로직 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/enums/CheckPhoneNumberType.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckPhoneNumberUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
account/src/test/kotlin/com/project/indistraw/service/CheckPhoneNumberServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/UpdatePasswordServiceTest.kt

- PASSWORD에서 -> FIND_ACCOUNT으로 enum 상수명을 변경 하였습니다.
- enum 타입에 따른 테스트 케이스를 추가하였습니다.

🔀 :: PASSWORD -> FIND_ACCOUNT 상수명 변경

---

.github/workflows/Django-CI.yml
.github/workflows/Spring-CI.yml

requirements.txt 파일 설치 후 commit 코드 추가했습니다.

requirements.txt 파일 설치 후 commit 코드 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/AddressRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/SignUpRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/Address.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AddressDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/SignUpDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Address.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/main/resources/static/roadSearch.html

- 다음 주소 검색 api를 활용한 html을 추가하였습니다.
- Account 도메인 모델들에 address 필드를 추가하였습니다.
- 다음 주소 api를 연동한 roadSearch.html을 추가하였습니다.

🔀 :: 주소 검색 html 추가

---

.github/workflows/Django-CI.yml
.github/workflows/Spring-CI.yml

Django.yml 파일의 push branch에 Spring 브랜치를 삭제하였고, Spring.yml 파일의 push branch에 Django 브랜치를 삭제하였습니다.

push branch 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandRefreshTokenPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/LogoutAccountUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandRefreshTokenPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/LogoutAccountService.kt
account/src/test/kotlin/com/project/indistraw/service/LogoutAccountServiceTest.kt

- 로그아웃 기능을 추가하였습니다.
- 로그아웃 요청을 하면 redis에 refreshToken hash를 삭제하도록 구현하였습니다.
- 해당 기능에 관한 테스트 코드를 추가하였습니다.

🔀 :: 로그아웃 기능 추가

---

account/src/test/kotlin/com/project/indistraw/common/AnyValueObjectGenerator.kt

- Address, AddressDto 타입을 추가했습니다.

🔀 :: Address, AddressDto 타입 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

- logout endPoint 권한 추가 코드를 추가하였습니다.
- logout start endpoint를 /account에서 /auth로 수정하였습니다.

:sparkles: :: logout endPoint 권한 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/SignUpRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountProfileDetailResponse.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/AccountEntity.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/SignUpDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

🔀 :: Address 필드 nullable로 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/Address.kt

🔀 :: Address nullable true로 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/AddressRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountProfileRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountProfileDetailResponse.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountProfileDetailDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AddressDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/UpdateAccountProfileDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountProfileService.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Account.kt
account/src/main/kotlin/com/project/indistraw/account/domain/Address.kt

- Address 필드 nullable 수정했습니다.
- 프로필 조회때 phoneNumber 컬럼도 추가하였습니다.

🔀 :: Address 필드 nullable 수정

---

account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

🔀 :: Rest하게 api 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/enums/CheckPhoneNumberType.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/UpdatePhoneNumberUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckPhoneNumberService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePhoneNumberService.kt
account/src/main/kotlin/com/project/indistraw/global/event/DeleteAuthenticationEventHandler.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/test/kotlin/com/project/indistraw/service/UpdatePhoneNumberServiceTest.kt

- 전화번호 변경 기능을 추가하였습니다.
- 전화번호 변경 요청하면 205 status를 보내도록 구현하였습니다.
- deleteAuthenticationEventHandler에서 authentication을 삭제해야하는데 save를 해서 해당 코드를 수정하였습니다.

🔀 :: 전화번호 변경 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/application/service/AccountProfileDetailService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/SignUpService.kt

🔀 :: 주소 null null로 오는 이슈 해결

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/TokenResponse.kt

🔀 :: jwt 만료시간 response json 포맷 추가

---

account/src/main/kotlin/com/project/indistraw/account/application/common/util/AuthenticationValidator.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdatePhoneNumberService.kt
account/src/test/kotlin/com/project/indistraw/service/UpdatePhoneNumberServiceTest.kt

- 전화번호 수정 안되는 이슈를 해결하였습니다.
- Redis Authentication 객체를 읽을때 Transaction 어노테이션을 추가하였습니다.
- 전화번호 수정 테스트 코드를 수정하였습니다.

🔀 :: 전화번호 수정 안되는 이슈 해결

---

account/src/test/kotlin/com/project/indistraw/service/AccountProfileDetailServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/UpdateAccountProfileServiceTest.kt

- 프로필 수정, 프로필 조회에서 안되는 테스트 코드를 수정하였습니다.

🔀 :: 안되는 테스트 코드 수정

---

.github/workflows/Spring-Account-CI.yml
.github/workflows/Spring-Crowdfunding-CI.yml

- Spring-CI working directory를 설정하였습니다.
- env 선언만 하고 working-directory에서 참조하지 않아 env를 참조하도록 변경하였습니다.

🔀 :: Spring-CI working directory 설정

---

search/search/settings.py

♻️  :: allow hosts 변경
운영시의 에러 때문에 allow hosts를 * 로 변경하였습니다.

♻️  :: allow hosts 변경

---

crowdfunding/build.gradle.kts
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewordRequest.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/CommandRewordPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryRewordPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/DateEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/RewordRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CrowdfundingDetailUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CrowdfundingListUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/SearchCrowdfundingUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingListDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingPagingDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewordDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryRewordPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/SearchCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Date.kt

🔀 :: 리스트, 디테일 조회 기능 추가

---

auth-agw/src/main/resources/application.yml

🔀 :: 크라우드 펀딩, 검색 서비스 gateway 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt

🔀 :: accountIdx -> idx로 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/request/UpdateAccountInfoRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/response/AccountInfoResponse.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/AccountProfileDetailUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/FindAccountInfoUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/UpdateAccountInfoUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountInfoDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/FindAccountInfoService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/UpdateAccountInfoService.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/test/kotlin/com/project/indistraw/service/AccountInfoServiceTest.kt
account/src/test/kotlin/com/project/indistraw/service/UpdateAccountInfoServiceTest.kt

🔀 :: profile -> info 로 네이밍 변경

---

account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
account/src/main/kotlin/com/project/indistraw/global/security/handler/CustomAccessDeniedHandler.kt

- accessDenidedHander 클래스를 만들고, securityConfig에서 처리 코드를 추가하였습니다.

🔀 :: 401, 403, 404 처리 로직 추가

---

crowdfunding/build.gradle.kts
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingListResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryRewordPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/CrowdfundingEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/CrowdfundingNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/UpdateCrowdfundingStatusUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingListDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/PopularCrowdfundingListService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/UpdateCrowdfundingStatusService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Crowdfunding.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/StatusType.kt
crowdfunding/src/main/resources/application.yml

- 크라우드 펀딩 status(심사중, 마감, 진행중) 수정 기능을 추가하였습니다.
- crowdfunding 도메인 필드인 activity를 status로 수정하였습니다.
- @Where 어노테이션을 삭제하고, JPA의 Not 쿼리 메서드로 대체 하였습니다.

🔀 :: 크라우드 펀딩 status 수정 기능 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/FindMyCrowdfundingListUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/FindMyCrowdfundingListService.kt

:sparkles: :: 자신이 작성한 크라우드 펀딩 리스트 조회 기능 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingPagingResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingPagingDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingListService.kt

- isLast라는 필드를 사용해서 pageSize라는 필드는 사용하지 않아 삭제하였습니다.

🔀 :: pageSize 필드 삭제

---

movie/api/models.py
movie/api/serializers.py
movie/api/urls.py
movie/api/views.py
movie/movie/settings.py
movie/movie/urls.py

영화부분을 추가로 작업하였습니다.
- 영화 히스토리 작업
- 영화 서치 
- 설정, Url 등의 가벼운 변동사항
아직 예외처리등의 작업이 완료되지 않았습니다. MSA 연동 이후에 유저 토큰이 어떤식으로 날라오는지에 따라서 로직? 이 조금 바뀔 것 같아 인증 인가와 관련된 코드는 짜두지 않았습니다.

🔀 :: 영화 히스토리 및 영화 부분 추가 작업, 다듬기

---

movie/Dockerfile
movie/api/models.py
movie/api/pagination.py
movie/api/producer.py
movie/api/serializers.py
movie/api/urls.py
movie/api/views.py
movie/consumer.py
movie/requirements.txt

MSA 연동 준비
- Dockerfile 작성
- requirements 업데이트
- consumer, producer 작성 완료
연동해보면서 지속적으로 수정해볼 예정입니다. 원활한 테스트를 위해 먼저 Django 브랜치에 병합하겠습니다.

🔀 :: MSA 연동 준비

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewordRequest.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewordConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/RewordEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/util/CalculateAmountUtil.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewordDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Reword.kt
crowdfunding/src/main/kotlin/com/project/indistraw/global/event/QueryCrowdfundingEventHandler.kt

- 리워드 도메인에 totalCount 필드를  추가하였습니다.
- totalAmount, targetAmoun 퍼센트 계산 이상한 이슈를 fix 하였습니다.

🔀 :: 리워드 totalCount 추가

---

movie/api/urls.py
movie/api/views.py

gitflow 꼬인거 정리하는 pr
명령어 잘못쳐서 꼬여가지고 억지로 푸쉬하고 머지하겠습니당

🐛 :: gitflow 꼬인거 정리하는 pr

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/RewardRequest.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingListResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/RewardResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/AmountEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/RewardEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/util/CalculateAmountUtil.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingListDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/RewardDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Amount.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Reward.kt

- totalAmount, targetAmount를 Long으로 수정하였습니다.
- percentage를 Double로 수정하였습니다.

🔀 :: Amount BigDecimal -> Long으로 수정

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/CrowdfundingDetailDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt

🔀 :: 남은 날짜 계산 안되는 이슈 해결

---

.github/workflows/Django-CI.yml
.github/workflows/Django-Movie-CD.yml
docker-compose.yml

장고 CICD 수정 및 docker-compose 작성
- CI 수정
- Django Movie CD 스크립트 작성
- docker-compose 1차 예시 작성
docker-compose 는 테스트용인점 참고 부탁드립니다!

🔀 :: 장고 CICD 수정 및 docker-compose 작성

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/feign/error/FeignClientErrorDecoder.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/feign/error/exception/FeignNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/ErrorCode.kt

🔀 :: Feign 404 예외처리 추가

---

.github/workflows/Django-Movie-CD.yml

.env 과정 추가했습니다.
.env 과정 추가했습니다.

🔀 :: .env 과정 추가

---

AI/Dockerfile

🔀 ::Dockerfile 오타수정

---

movie/api/views.py

테스트용으로 Description 부분을 삭제하고 pr 날립니다
테스트용으로 Description 부분을 삭제하고 pr 날립니다

🔀 :: 테스팅 PR 및 description 부분 삭제

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/AccountWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/AuthWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AuthDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/request/SignInRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/request/SignUpRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/request/UpdateAccountInfoRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/request/UpdateAddressRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/request/UpdatePasswordRequest.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/response/AccountInfoResponse.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/response/TokenResponse.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandQRCodeUUIDPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryAccountPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryQRCodeUUIDPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/GenericConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AccountConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AuthCodeConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/AuthenticationConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/QRCodeUUIDConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/common/converter/RefreshTokenConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/entity/QRCodeUUIDEntity.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/repository/QRCodeUUIDRepository.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CommandQRCodeUUIDPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/QueryQRCodeUUIDPort.kt
account/src/main/kotlin/com/project/indistraw/account/domain/QRCodeUUID.kt

- crowdfunding 서버는 request, response 패키지를 data 패키지로 감싸서 account 서버도 동일하게 패키지를 추가하였습니다.
- genericConverter 인터페이스를 추가하고 각 converter에 구현하였습니다.

🔀 :: QRCodeUUID 세팅

---

movie/consumer.py

import 위치 변경(인터프리터 언어라..)
import 위치 변경(인터프리터 언어라..)

🔀  :: import 위치 변경(인터프리터 언어라..)

---

AI/AI/settings.py
movie/movie/settings.py

allow hosts 추가
운영을 위해서 allow hosts 를 추가하였습니다.

🔀  :: allow hosts 추가

---

movie/consumer.py

movie consumer쪽에 create_account 기능을 추가하였습니다.
movie consumer쪽에 create_account 기능을 추가하였습니다.

🔀  ::create_account 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/CommandQRCodeUUIDPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/persistence/QueryQRCodeUUIDPersistenceAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/redis/RedisPubSubAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/error/ErrorCode.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/InvalidQRCodeUUIDException.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckQRCodeUUIDUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckSSEPingUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CreateQRCodeUUIDUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/CommandQRCodeUUIDPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/QueryQRCodeUUIDPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/RedisPubSubPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/TokenParsePort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckQRCodeUUIDService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckSSEPingService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CreateRCodeUUIDService.kt
account/src/main/kotlin/com/project/indistraw/global/redis/RedisConfig.kt
account/src/main/kotlin/com/project/indistraw/global/redis/property/RedisProperties.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/TokenParseAdapter.kt

- redisConfig, redisProperties 클래스를 추가하였습니다.
- redis pub/sub 기능을 토대로 한 SSE 통신을 구현하였습니다.
- QRCode UUID 생성, 검증 로직을 추가하였습니다.
- 일단 기능 구현을 1순위로 코드를 작성한거기 때문에 코드가 많이 더럽습니다.. 추후 이 기능이 제대로 동작 한다면 리펙토링을 진행할 예정입니다.

🔀 :: QR Code 로그인 기능 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/QRCodeWebAdapter.kt

🔀 :: qrCodeWebAdapter 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/dto/CrowdfundingInfoDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/global/event/CreateCrowdfundingEvent.kt
crowdfunding/src/main/kotlin/com/project/indistraw/global/event/CreateCrowdfundingEventHandler.kt
crowdfunding/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/config/RabbitMQConfig.kt
crowdfunding/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQCreateCrowdfundingPublisher.kt

- 크라우드 펀딩이 생성 됐을때 publish 하기위한 rabbitMQ 세팅을 하였습니다.

🔀 :: rabbitMQ 세팅 추가

---

account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

🔀 :: qr-code endpoint 추가

---

AI/consumer.py

🔀:: 큐 이름 수정

---

movie/api/views.py

publish_data 변수 추가
publish_data를 추가해줘서 publisher가 AI consumer에게 올바른 데이터를 전달할 수 있도록 하였습니다.

🔀 :: publish_data 변수 추가

---

movie/api/views.py

json 으로 변환
publisher Data를 json으로 변환시켜줍니다.

🔀 : :: json 으로 변환

---

movie/api/views.py

보내는 형식 변경
producer가 consumer쪽으로 보내는 형식 변경하였습니다.

🔀  :: 보내는 형식 변경

---

movie/api/views.py

account index 추가
account index 추가

🔀  :: account index 추가

---

AI/consumer.py
AI/recommandation/tests.py

🔀:: consumer 파일 데이터 구조 변경

---

AI/consumer.py
AI/recommandation/tests.py

🔀 :: consumer 파일 람다표현식 수정

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/QRCodeWebAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/redis/RedisPubSubAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/CheckSsePingUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/ConnectSseUseCase.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/RedisPubSubPort.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckQRCodeUUIDService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CheckSsePingService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/ConnectSseService.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/CreateRCodeUUIDService.kt
account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

- sse connect 컨트롤러, 로직을 기존 uuid 생성에서 분리하였습니다.
- sseEmitter를 리턴하도록 구현하였습니다.
- qrCodeUUID 검증에 대한 endPoint에 권한을 추가하였습니다.

🔀 :: sse connect 로직 분리

---

AI/consumer.py

🔀 :: consumer.py 코드 수정

---

search/Dockerfile
search/api/models.py
search/api/pagination.py
search/api/serializers.py
search/api/urls.py
search/api/views.py
search/requirements.txt
search/search/settings.py

연관검색어, 인기 태그 기능 추가
- 연관 검색어 리팩토링
- 인기 태그 기능 추가
갈 길이 머네요. 백엔드 너무 어렵습미다 ㅠ

🔀 :: 연관검색어, 인기 태그 기능 추가

---

AI/AI/urls.py
AI/consumer.py
AI/recommandation/admin.py
AI/recommandation/serializers.py
AI/recommandation/tests.py
AI/recommandation/urls.py
AI/recommandation/views.py

🔀 :: consumer data 배열화

---

AI/anti_porno/tests.py
AI/consumer.py

🔀 :: 내부 딕셔너리 확인

---

AI/consumer.py

🔀 :: 로그 확인

---

AI/consumer.py

🔀 :: consumer 인덱스 문제 수정

---

AI/consumer.py

🔀 :: consumer 인덱스 문제 예외 추가

---

AI/consumer.py

🔀 :: consumer 인덱스 문제 확인

---

AI/anti_porno/tests.py
AI/consumer.py

🔀 :: json변환코드 추가

---

AI/consumer.py

🔀 :: 문자열처리 문제 수정

---

AI/consumer.py
AI/recommandation/views.py

🔀 :: db 에러수정

---

AI/consumer.py
AI/recommandation/admin.py
AI/recommandation/models.py
AI/recommandation/serializers.py
AI/recommandation/tests.py
AI/recommandation/views.py

🔀 :: 모델이름 CamelCase 수정

---

AI/recommandation/consumer.py

🔀 :: consumer 파일 구조 변경

---

AI/recommandation/consumer.py

🔀 :: consumer 파일 구조 변경에 따른 모듈 이름 변경

---

gateway/src/main/resources/application.yml

🔀 :: qr-code/check/{uuid} -> qr-code/signin으로 수정

---

AI/consumer.py

🔀 :: 모듈이름 우회

---

AI/Dockerfile
AI/consumer.py

🔀 :: Dockerfile 수정

---

AI/Dockerfile
AI/consumer.py

🔀 :: 환경변수 설정 변경

---

account/Dockerfile

🔀 :: Dockerfile 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/output/sse/SseEmitterAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/output/dto/TokenDto.kt

- toString이라기 보단 toJson이 맞는거 같긴 하지만 기존에 object를 response 해주던 걸 json으로 바꿨습니다.

🔀 :: tokenDto toString 메서드 추가

---

crowdfunding/Dockerfile
crowdfunding/src/main/resources/application.yml

- 기존 8081 포트에서 띄우다가 8080으로 수정하였습니다.

🔀 :: docker file 추가

---

movie/api/serializers.py
movie/api/views.py
movie/movie/settings.py

요청사항대로 변경
페이징 삭제, 형식 변경 등등 클라이언트의 요청과 명세서대로 맞췄습니다#148

🔀 :: 요청사항대로 변경

---

gateway/Dockerfile

🔀 :: Gateway Dockerfile 추가

---

movie/api/models.py

jsonfield로 수정
기존 foreignkey로 쓰던거 결국 array로 받아야하기때문에 jsonfield로 변경하였습니다.

🔀 :: jsonfield로 수정

---

account/src/main/kotlin/com/project/indistraw/account/application/port/output/dto/TokenDto.kt

- tokenDto의 toSting 메서드의 LocalDateTime 부분 쌍따음표를 추가하였습니다.
- date format을 로그인, 토큰 재발급이랑 같게 수정하였습니다.

🔀 :: 쌍따음표 추가

---

account/src/main/kotlin/com/project/indistraw/account/adapter/input/converter/AccountDataConverter.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/input/data/response/AccountInfoResponse.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/sse/SseEmitterAdapter.kt
account/src/main/kotlin/com/project/indistraw/account/application/port/input/dto/AccountInfoDto.kt
account/src/main/kotlin/com/project/indistraw/account/application/service/FindAccountInfoService.kt

- 클라이언트에게 메세지를 보내기 전에 complete 메서드를 통해 커넥션을 닫아버려서 메세지를 보낸 후 커넥션을 닫도록 수정하였습니다.
- 메세지를 발송하면 map remove 메서드를 호출하였습니다.

🔀 :: sse 400 계속 뜨는 이슈 해결

---

account/src/main/kotlin/com/project/indistraw/account/adapter/output/message/exception/MessageSendFailedException.kt
account/src/main/kotlin/com/project/indistraw/account/adapter/output/sse/exception/InvalidSseConnectionException.kt
account/src/main/kotlin/com/project/indistraw/account/application/common/error/exception/IndiStrawAccountException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/AccountNotFoundException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/AuthCodeNotFoundException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/AuthCodeNotMatchException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/AuthenticationNotFoundException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedAccountIdException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedNewPasswordException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/DuplicatedPhoneNumberException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/InvalidQRCodeUUIDException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/PasswordNotMatchException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/TooManyAuthCodeRequestException.kt
account/src/main/kotlin/com/project/indistraw/account/application/exception/TooManyAuthenticationRequestException.kt
account/src/main/kotlin/com/project/indistraw/global/error/ErrorCode.kt
account/src/main/kotlin/com/project/indistraw/global/error/exception/IndiStrawAccountException.kt
account/src/main/kotlin/com/project/indistraw/global/error/handler/GlobalExceptionHandler.kt
account/src/main/kotlin/com/project/indistraw/global/error/response/ErrorResponse.kt
account/src/main/kotlin/com/project/indistraw/global/security/filter/ExceptionHandlerFilter.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/ExpiredRefreshTokenException.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/InvalidTokenException.kt
account/src/main/kotlin/com/project/indistraw/global/security/token/common/exception/InvalidTokenTypeException.kt
account/src/test/kotlin/com/project/indistraw/service/AccountInfoServiceTest.kt

- application(core) 계층에 전역적인 exception 처리가 이뤄져서 global 계층으로 이전 시켰습니다.
- build가 돌아가지 않는 테스트 코드를 수정하였습니다.

🔀 :: exception 처리 패키지 global 계층으로 이전

---

gateway/src/main/resources/application.yml

🔀 :: Movie Route 추가

---

file/Dockerfile

Dockerfile 생성
파일 서버의 배포를 위해서 Dockerfile을 생성하였습니다.

🔀 :: Dockerfile 생성

---

.github/workflows/Django-File-CD.yml

CD 스크립트 작성
Django-FIle 서버의 CD 스크립트를 작성하였습니다.

🔀 :: Django-File-CD 작성 완료

---

file/api/views.py

🔀 :: CD를 위한 테스트 커밋

---

file/api/urls.py

url name 추가
테스트 커밋을 위해 url name 추가만 하고 pr 날립니다.

🔀 :: url name 추가

---

file/Dockerfile
file/api/urls.py

🔀 :: dodckerfile 변경

---

movie/api/models.py
movie/api/serializers.py
movie/api/urls.py
movie/api/views.py
movie/movie/settings.py

요청사항에 따라 response, request 등을 변경하였습니다.
- db 리펙토링
- response, request 리팩토링
아직 리팩토링 해야하는 로직들이 조금 남았습니다. 오늘 내로 끝내보도록할게요.

♻️ :: 요청사항에 따라 response, request 등 변경

---

.github/workflows/Spring-Account-CI.yml
.github/workflows/Spring-Crowdfunding-CI.yml
.github/workflows/Spring-Funding-CI.yml
.github/workflows/Spring-Gateway-CI.yml

- Spring-Funding-Ci.yml, Spring-Gateway-CI.yml 스크립트를 추가하였습니다.

🔀 :: Gateway, Funding 서버 CI 스크립트 추가

---

movie/requirements.txt

requirements 업데이트
requirements 업데이트

🔀 :: requirements 업데이트

---

movie/api/models.py

movie_idx 다시 활성화
movie_idx 다시 활성화

🔀 :: movie_idx 다시 활성화

---

movie/api/views.py

필드명 수정으로 인한 수정
필드명 수정으로 인한 컨트롤러 수정

🐛 :: 필드명 수정으로 인한 수정

---

.idea/misc.xml
AI/AI/settings.py
AI/consumer.py
AI/recommandation/models.py
AI/recommandation/views.py
AI/requirements.txt

🔀 :: postgresql로 DB변경

---

funding/build.gradle.kts
funding/src/main/kotlin/com/project/indistraw/IndistrawFundingApplication.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/CommandFundingPersistenceAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/GenericConverter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/converter/FundingConverter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/entity/BaseIdxEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/entity/BaseTimeEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/entity/FundingEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/repository/FundingRepository.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/common/annotation/Aggregate.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/common/annotation/AggregateRoot.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/common/annotation/ServiceWithReadOnlyTransaction.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/common/annotation/ServiceWithTransaction.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/output/AccountSecurityPort.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/output/CommandFundingPort.kt
funding/src/main/kotlin/com/project/indistraw/funding/domain/Activity.kt
funding/src/main/kotlin/com/project/indistraw/funding/domain/Funding.kt
funding/src/main/kotlin/com/project/indistraw/global/security/adapter/AccountSecurityAdapter.kt
funding/src/main/kotlin/com/project/indistraw/global/security/config/FilterConfig.kt
funding/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt
funding/src/main/kotlin/com/project/indistraw/global/security/filter/AuthenticationFilter.kt
funding/src/main/kotlin/com/project/indistraw/global/security/handler/CustomAccessDeniedHandler.kt
funding/src/main/kotlin/com/project/indistraw/global/security/handler/CustomAuthenticationEntryPoint.kt
funding/src/main/kotlin/com/project/indistraw/global/security/token/TokenParser.kt
funding/src/main/kotlin/com/project/indistraw/global/security/token/common/emums/Authority.kt
funding/src/main/kotlin/com/project/indistraw/global/security/token/common/property/JwtProperties.kt

- funding 애그리거트를 추가하였습니다.
- funding 도메인을 영속화 하기 위한 fundingEntity를 추가하였습니다.
- security 관련된 코드를 추가하였습니다.
- 프로젝트에 사용하는 의존성들을 추가하였습니다.

🔀 :: Funding Security, Jpa 세팅 추가

---

.github/workflows/Spring-Account-CD.yml

- Spring-Account 서버의 CD를 추가하였습니다.

🔀 :: Spring Account CD 추가

---

account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQCreateAccountPublisher.kt
account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQDeleteAccountPublisher.kt

- 각 서버에 계정이 생성될때, 삭제될때 accountIdx 로그를 추가하였습니다.

🔀 :: Publish AccountIdx 로그 추가

---

account/src/main/kotlin/com/project/indistraw/thirdparty/rabbitmq/publisher/RabbitMQCreateAccountPublisher.kt

🔀 :: Publisher ContentType 지정

---

.github/workflows/Spring-Account-CD.yml

🔀 :: FILE -> ACCOUNT로 수정

---

account/src/main/kotlin/com/project/indistraw/global/security/config/SecurityConfig.kt

🔀 :: SecurityConfig 가독성을 위해 메서드로 분리

---

account/Dockerfile

- dockerfile workdir을 지정하여 실행 디렉토리를 지정하였습니다.

🔀 :: 실행 디렉토리 추가

---

funding/src/main/kotlin/com/project/indistraw/global/error/ErrorCode.kt
funding/src/main/kotlin/com/project/indistraw/global/error/exception/IndiStrawFundingException.kt
funding/src/main/kotlin/com/project/indistraw/global/error/handler/GlobalExceptionHandler.kt
funding/src/main/kotlin/com/project/indistraw/global/error/response/ErrorResponse.kt
funding/src/main/resources/application.yml

🔀 :: 전역 예외처리 로직 추가

---

funding/src/main/kotlin/com/project/indistraw/funding/adapter/input/FundingWebAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/pay/PayAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/pay/exception/FailedPayCancelException.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/pay/exception/FailedPayConfirmException.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/CommandFundingPersistenceAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/QueryFundingPersistenceAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/converter/FundingConverter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/entity/BaseTimeEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/entity/FundingEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/exception/FundingNotFoundException.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/input/CancelFundingUseCase.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/output/CommandFundingPort.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/output/QueryFundingPort.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/service/CancelFundingService.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/service/SaveFundingService.kt
funding/src/main/kotlin/com/project/indistraw/global/error/ErrorCode.kt

🔀 :: 결제 취소 기능 추가

---

funding/build.gradle.kts
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/consumer/CreateCrowdfundingConsumeAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/CommandCrowdfundingPersistenceAdapter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/common/converter/CrowdfundingConverter.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/entity/CrowdfundingEntity.kt
funding/src/main/kotlin/com/project/indistraw/funding/adapter/output/persistence/repository/CrowdfundingRepository.kt
funding/src/main/kotlin/com/project/indistraw/funding/application/port/output/CommandCrowdfundingPort.kt
funding/src/main/kotlin/com/project/indistraw/funding/domain/Crowdfunding.kt
funding/src/main/resources/application.yml

- MSA 환경에서 데이터 동기화를 위한 크라우드 펀딩 Consumer를 추가하였습니다.
- 제가 보기에도 그렇게 좋은 구조는 아니라고 생각합니다.
지금은 어거지로 돌아가기 위한 구조로 돌아가고 있어 추후 리펙토링을 진행시켜 더 좋은 구조로 개선시키겠습니다.

🔀 :: 크라우드 펀딩 Consumer 추가

---

gateway/src/main/resources/application.yml

🔀 :: SSL/TLS 비활성화 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/FundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/pay/PayAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/pay/exception/FailedPayCancelException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/pay/exception/FailedPayConfirmException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/CommandFundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryFundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/FundingConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/AccountEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/AddressEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/FundingEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/AccountRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/FundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/ErrorCode.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/AccountNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/InvalidReceiptIdException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/ReceiptIdNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/RewardNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/SaveFundingUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/SaveFundingDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/CommandFundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/PayPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryPayInfoPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/SaveFundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Account.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Funding.kt

- bootpay 검증, 취소 메서드를 작성했습니다.
- receiptId를 String으로 전체 통일 시켰습니다.
- 존재하지 않은 receiptId라면 예외를 발생시키게 구현하였습니다.

🔀 :: Funding 저장 로직 추가

---

AI/consumer.py
AI/recommandation/models.py
AI/recommandation/serializers.py
AI/recommandation/urls.py
AI/recommandation/views.py

🔀  :: 추천알고리즘 구현 완료

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/FundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/PayInfoEntity.kt
crowdfunding/src/main/resources/application.yml

- 환경변수에 오타가 있는 문제를 해결하였습니다.
- id 어노테이션을 잘못 import한 문제를 해결하였습니다.

🔀 :: 환경변수 키워드 수정

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryFundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryPayInfoPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/FundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/PayInfoRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/ErrorCode.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/FundingNotFoundException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/CancelFundingUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryFundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CancelFundingService.kt

🔀 :: 결제 취소 로직 추가

---

search/api/models.py
search/api/serializers.py
search/api/urls.py
search/api/views.py
search/consumer.py
search/crowd_consumer.py

명세서 따라 작업(리팩토링) 및 추가 기능들
- search 관련 로직 리사이클링
- movie consumer, crowd conumser 생성
- 영화 서치 관련 기능 추가

🔀 :: 명세서 따라 작업 및 추가 기능들

---

AI/AI/urls.py
AI/test.py

🔀  :: 엔드 포인트 변경

---

.github/workflows/Spring-Gateway-CI.yml

🔀 :: jdk 17로 변경

---

crowdfunding/build.gradle.kts
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/FundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/FundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/request/SaveFundingRequest.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/entity/FundingEntity.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CustomCrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/publisher/CrowdfundingPublishAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/FindMyFundingListUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/dto/CrowdfundingDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/FindMyFundingListService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/global/config/QueryDslConfig.kt

- queryDsl에 대한 의존성을 추가하고, queryDslConfig 클래스를 추가하였습니다.
- 크라우드 펀딩 생성 publisher에서 title 값만 반환하게 변경하였습니다.

🔀 :: 펀딩한 리스트 조회 기능 추가

---

gateway/build.gradle.kts
gateway/src/main/resources/application.yml

- multipart file 최대 허용 범위, 요청 허용 범위를 설정하였습니다.
- ai, funding 라우팅을 추가하였습니다.

🔀 :: multipart file 사이즈 지정

---

movie/actor/admin.py
movie/actor/apps.py
movie/actor/models.py
movie/actor/tests.py
movie/actor/views.py
movie/api/models.py
movie/api/serializers.py
movie/api/urls.py
movie/api/views.py
movie/director/admin.py
movie/director/apps.py
movie/director/models.py
movie/director/tests.py
movie/director/views.py
movie/history/admin.py
movie/history/apps.py
movie/history/models.py
movie/history/tests.py
movie/history/views.py

🔀 :: 리팩토링 및 요구사항 진행

---

file/file/settings.py

🔀 :: 최대 용량 변경

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/MyCrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryFundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CustomCrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/common/error/ErrorCode.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/exception/NotMyCrowdfundingException.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/MyCrowdfundingDetailUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/AccountInfoDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/input/dto/MyCrowdfundingDetailDto.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryFundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/MyCrowdfundingDetailService.kt

- 자신이 작성한 크라우드 펀딩이면 디테일 조회되는 기능을 추가하였습니다.
- 자신이 작성한게 아니라면 400 status를 반환하도록 구현하였습니다.

🔀 :: 내가 쓴 크라우드 펀딩 디테일 조회 기능 추가

---

search/api/serializers.py

🔀 :: 테스트 커밋

---

search/search/settings.py

🔀  :: db 변경

---

search/api/views.py

페이징 삭제 및 데이터 갯수 제한
페이징 삭제 및 데이터 갯수 제한

🔀 :: 페이징 삭제 및 데이터 갯수

---

file/file/settings.py

🔀 :: 파일 용량 변경

---

file/api/views.py

🔀 :: 받는 방식 변경

---

file/api/views.py

🔀 :: recycle

---

AI/AI/urls.py
AI/recommandation/tests.py

🔀 :: path 추가

---

AI/AI/urls.py
AI/anti_porno/views.py
AI/recommandation/views.py

🔀  :: banner api 추가

---

AI/recommandation/views.py

🔀  :: banner api 수정

---

AI/AI/urls.py

:recycle: :: banner api 수정

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/CrowdfundingWebAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryCrowdfundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CustomCrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryCrowdfundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/SearchCrowdfundingUseCase.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/SearchCrowdfundingService.kt

🔀 :: 크라우드 펀딩 검색 페이징 처리 추가

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CustomCrowdfundingRepository.kt

- 자신이 펀딩한 크라우드 펀딩을 가져오는 queryDsl에서 오류가 난것을 fix 하였습니다.

🔀 :: Join 안되는 이슈 해결

---

AI/recommandation/views.py

🔀 :: response 추가

---

movie/consumer.py

🔀 :: cd용 커밋

---

AI/consumer.py

🔀  :: consumer 수정

---

AI/consumer.py

🔀 :: data fomat change

---

AI/consumer.py

🔀  :: data fomat change

---

movie/api/views.py

:bug: :: 들여쓰기

---

search/api/views.py

:bug: :: 픽스

---

AI/AI/urls.py
AI/recommandation/views.py

🔀 :: 컨슈머 파링 수정

---

search/api/models.py

:bug: :: 맥스 length 수정

---

search/consumer.py

:bug: :: fix

---

movie/api/views.py

:recycle: :: genre 관련 이슈 수정

---

AI/recommandation/views.py

🔀 :: 추천,인기데이터 더미로 변경

---

crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/converter/CrowdfundingDataConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/input/data/response/CrowdfundingDetailResponse.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/CommandRewardPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryFundingPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/QueryRewardPersistenceAdapter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/common/converter/RewardConverter.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/CustomCrowdfundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/adapter/output/persistence/repository/FundingRepository.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/CommandRewardPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryFundingPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/port/output/QueryRewardPort.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CreateCrowdfundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/CrowdfundingDetailService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/application/service/SaveFundingService.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Crowdfunding.kt
crowdfunding/src/main/kotlin/com/project/indistraw/crowdfunding/domain/Reward.kt

🔀 :: 크라우드 펀딩 금액 증가, 리워드 수 차감 구현
